REM Usage ./FitnessFillSpaceSnakes.bat <seed>
cd..
python main.py --BASE_DIR=fill --EXPERIMENT_PREFIX=snakes --RANDOM_SEED=%1 --POPULATION_SIZE=100 --INTERACTIVE_EVOLUTION=False --SAVE_FITNESS_LOG=True --POTENTIAL_BLOCK_SET=machine --FITNESS_FUNCTION=occupied_count --EVOLVE_SNAKE=True --CONFINE_SNAKES=True --REDIRECT_CONFINED_SNAKES=True --USE_ELITISM=True --EVOLVE_FITNESS=True
