cd..
python main.py --BASE_DIR=%1 --EXPERIMENT_PREFIX=%2 --RANDOM_SEED=%3 --POPULATION_SIZE=%4 --INTERACTIVE_EVOLUTION=False --SAVE_FITNESS_LOG=True --POTENTIAL_BLOCK_SET=machine --FITNESS_FUNCTION=type_count --DESIRED_BLOCK=QUARTZ_BLOCK
