REM Usage ./FitnessTargetQuartzCubes.bat <seed>
cd..
python main.py --BASE_DIR=target --EXPERIMENT_PREFIX=quartz120cubes --RANDOM_SEED=%1 --POPULATION_SIZE=100 --INTERACTIVE_EVOLUTION=False --SAVE_FITNESS_LOG=True --POTENTIAL_BLOCK_SET=machine --FITNESS_FUNCTION=type_target --DESIRED_BLOCK=QUARTZ_BLOCK --DESIRED_BLOCK_COUNT=120 --USE_ELITISM=True --EVOLVE_FITNESS=True